export class UserModel {

    readonly userId: string; // generated by db
    readonly email: string;
    readonly password: string;
    readonly role: string; // user or admin

    constructor($userId: string, $email: string, $password: string, $role: string) {
      this.userId = $userId;
      this.email = $email;
      this.password = $password;
      this.role = $role;
    }

}
